### PR TITLE
[favorites] Favorites

### PR DESCRIPTION
**Pull request by mtwebster**
ref:
https://github.com/linuxmint/cinnamon/pull/8936
https://github.com/linuxmint/nemo/pull/2527
https://github.com/linuxmint/xed/pull/409

### CODE REVIEW

**Comment by ItzSwirlz** [comment]
Build succeeded on arm64

Here are some warnings left behind:

/home/jpeisach/Desktop/cinnamon/xapp/libxapp/xapp-favorites.h:38: warning: Field description for XAppFavoriteInfo::display_name is missing in source code comment block.
/home/jpeisach/Desktop/cinnamon/xapp/libxapp/xapp-favorites.h:38: warning: Field description for XAppFavoriteInfo::cached_mimetype is missing in source code comment block.
/home/jpeisach/Desktop/cinnamon/xapp/libxapp/xapp-favorites.h:38: warning: Field description for XAppFavoriteInfo::mimetype is not used from source code comment block.
/home/jpeisach/Desktop/cinnamon/xapp/libxapp/xapp-favorites.h:38: warning: Field description for XAppFavoriteInfo::index is not used from source code comment block.
unknown:0: warning: Field descriptions for struct XAppGtkWindowClass are missing in source code comment block.
unknown:0: warning: Value descriptions for XAppIconSize are missing in source code comment block.

**Comment by ItzSwirlz** [comment]
Build also suceeded, so did Nemo and Cinnamon on arm64.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/xapp/commit/c9c885a84143763c22ec98522a46fcb2807b420c

**Comment by mtwebster** [comment]
arm64? Does cinnamon run on this? I've never paid much attention to raspberry pi, etc.. does muffin build?

**Comment by leigh123linux** [comment]
> arm64? Does cinnamon run on this? I've never paid much attention to raspberry pi, etc.. does muffin build?

The whole cinnamon stack builds ok for armv7hl i686 x86_64 aarch64 ppc64le  and s390x

**Comment by ItzSwirlz** [comment]
My Pi 4 came in recently, along with my first ever monitor :D 

Here is a picture of it in action, running Ubuntu 20.10 (twitter post), and actually it isn't working somewhere (probably muffin) but here it is:
https://twitter.com/ItzSwirlz/status/1327043696546734080

I can also setup a **Launchpad Repository** to build Cinnamon for all arch's I can find automatically for CI if you wish (every now and then)

Considering I want to eventually be able to get [UCR to Pi support](https://github.com/Ubuntu-Cinnamon-Remix/pi-img-builder) (dont know how I'll find a good image builder), it's just baby steps.

**Pull request closed without merging**
